version: "3"

services:
  predictor:
    build: .
    image: predictor:week2
    ports:
      - "8080:8080"
    volumes:
      - ./test_dir:/opt/ml
    entrypoint: serve
    
  redis:
    image: "redis:alpine"